/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); see LICENSE.
 */

// Mirror of res/values/strings.xml (R.string). Auto-generated during the
// Android -> iOS conversion. Korean entries preserved verbatim; %s/%d style
// format specifiers are kept as-is and used with String(format:).
import Foundation

enum Str {
  static let aboutThisUpdate = "About this update"
  static let all = "All"
  static let add = "Add"
  static let added = "Added"
  static let addAudio = "+Audio"
  static let aicoreAccessPanelTitle = "You cannot access this model yet. Please follow the steps and return when complete."
  static let aicoreAccessPanelButton = "Open guide"
  static let aicoreImageLimitMessage = "The current model can only support 1 image per chat. To ask about another image, create a new chat."
  static let aichatInitializingTitle = "Initializing model"
  static let aichatInitializingContent = "Sit tight, this can take up to 1 minute"
  static let appIntro = "Explore a world of amazing on-device models from"
  static let appName = "찐친 Ai"
  static let appNameFirstPart = "찐친"
  static let appNameSecondPart = "Ai"
  static let paywallProBadge = "Pro"
  static let paywallTitle = "Enjoy The Best Chat Experience"
  static let paywallFeature1 = "NSFW 필터와 모든 AI 캐릭터의 잠금을 해제하세요."
  static let paywallFeature2 = "무제한적인 개인적인 로맨틱한 대화"
  static let paywallFeature3 = "더 똑똑해진 모델과 더 긴 메모리"
  static let paywallFeature4 = "무제한 개인 AI 친구 맞춤 제작"
  static let paywallFeature5 = "더 많은 인기 콘텐츠를 점점 해제하고 50% 이상의 할인을 즐기세요"
  static let paywallFeature6 = "광고 제거"
  static let paywallFeature7 = "지금 가입하면 선물 600 코인을 드립니다."
  static let paywallPlanWeekly = "Weekly"
  static let paywallPlanMonthly = "Monthly"
  static let paywallPlanYearly = "Yearly"
  static let paywallBadgeBestValue = "BEST VALUE"
  static let paywallBadgeMostPopular = "MOST POPULAR"
  static let paywallPriceWeekly = "₩1,000"
  static let paywallPriceMonthly = "₩24,000"
  static let paywallPriceYearly = "₩48,000"
  static let paywallCta = "결제 %1$s 지금"
  static let paywallClose = "닫기"
  static let voiceSettingsTitle = "설정"
  static let askimageEmptystateTitle = "Ask Image"
  static let askimageEmptystateContent = "To get started, tap the + below to add an image (max 10 images per chat) and type a prompt to ask a question about it!"
  static let askimageEmptystateContentAicore = "To get started, tap the + below to add an image (max 1 image per chat) and type a prompt to ask a question about it!"
  static let askaudioEmptystateTitle = "Ask Audio"
  static let askaudioEmptystateContent = "To get started, tap the + below to add a audio clip (limited to 1 clip up to 30 seconds) and type a prompt to transcribe or translate it!"
  static let galleryNewsNotificationTitle = "Gallery News"
  static let baseline = "Baseline"
  static let basicInfo = "Basic info"
  static let benchmark = "Benchmark"
  static let benchmarkComparisonHelpTitle = "How to compare benchmark runs"
  static let benchmarkComparisonHelpContent = "Compare benchmark runs by tapping the **Baseline** chip on any run result card to set the run as the comparison baseline. We'll automatically calculate and display the percentage differences in **all other** run result cards."
  static let benchmarkModel = "Benchmark model"
  static let benchmarkResults = "Benchmark results"
  static let benchmarkNoResults = "No benchmark results"
  static let benchmarkTokensLimitMessage = "Ensure that the sum of prefill and decode tokens remains under the model's maximum token limit (%d vs %d)"
  static let bestOverall = "Best overall"
  static let modelListExperimentalLabel = "EXPERIMENTAL"
  static let cancel = "Cancel"
  static let categoryUnlabeled = "Unlabeled"
  static let categoryLlm = "LLM"
  static let categoryAgents = "Agents"
  static let categoryClassicalMl = "Classical ML"
  static let categoryExperimental = "Experimental"
  static let chatTextinputPlaceholder = "Type message…"
  static let chatYou = "You"
  static let chatLlmAgentName = "LLM"
  static let showThinking = "Show thinking"
  static let checkingAccess = "Checking access..."
  static let close = "Close"
  static let collapseAll = "Collapse all"
  static let discard = "Discard"
  static let discardChangesDialogTitle = "Discard changes?"
  static let discardChangesDialogContent = "You have unsaved changes. Are you sure you want to discard them?"
  static let deleteBenchmarkResultDialogTitle = "Delete benchmark result"
  static let deleteBenchmarkResultDialogContent = "Are you sure you want to delete the benchmark result?"
  static let error = "Error"
  static let confirmDeleteModelDialogTitle = "Delete download"
  static let confirmDeleteModelDialogContent = "Are you sure you want to delete the downloaded model \"%s\"?"
  static let conversationResetMessage = "Conversation was reset"
  static let enginResetMessage = "Engine was reset"
  static let chatAgentAgentName = "Agent"
  static let chatGenericAgentName = "Model"
  static let chatGenericResultName = "Result"
  static let clear = "Clear"
  static let collect = "Collect"
  static let color = "Color"
  static let configDialogTabModelConfigs = "Model configs"
  static let configDialogTabSystemPrompt = "System prompt"
  static let continueButtonLabel = "Continue"
  static let conversationHistory = "Conversation History"
  static let copy = "Copy"
  static let create = "Create"
  static let delete = "Delete"
  static let descriptionRequired = "Description*"
  static let disabled = "Disabled"
  static let dismiss = "Dismiss"
  static let done = "Done"
  static let download = "Download"
  static let downloadedSize = "%1$s downloaded"
  static let drawerSettingsLabel = "Settings"
  static let drawerSettingsDescription = "Manage application settings"
  static let drawerModelsLabel = "Models"
  static let drawerModelsDescription = "Browse, try, and benchmark models"
  static let drawerNotificationsLabel = "Notifications"
  static let drawerNotificationsDescription = "View scheduled notifications"
  static let notificationsTitle = "Notifications"
  static let notificationsEmptyState = "No scheduled notifications"
  static let notificationsDeleteDialogTitle = "Delete Notification"
  static let notificationsDeleteDialogContent = "Are you sure you want to delete the scheduled notification \"%s\"?"
  static let notificationsTimeLabel = "Time: %s"
  static let notificationsDateLabel = "Date: %s"
  static let notificationsRepeatDaily = "Daily"
  static let notificationsRepeatOneTime = "One-time"
  static let edit = "Edit"
  static let editSecret = "Edit secret"
  static let enterInstruction = "Enter instruction"
  static let expandAll = "Expand all"
  static let failedToSave = "Failed to save"
  static let flashlightOffMessage = "I've turned off the flashlight."
  static let flashlightOnMessage = "I've turned on the flashlight."
  static let functionName = "Function name"
  static let generateAndCopy = "Generate and copy"
  static let grantPermissions = "Grant permissions"
  static let grantRecordAudioPermission = "Grant record audio permission"
  static let holdDownToTalk = "Hold to talk"
  static let inputHistory = "Input history"
  static let instructions = "Instructions"
  static let introducing = "Introducing"
  static let invalidResponse = "Invalid response"
  static let learnMore = "Learn more and see model license"
  static let listening = "Listening..."
  static let litertCommunityLabel = "LiteRT community"
  static let loadingModelList = "Loading model list..."
  static let logsViewerFilterTextInputPlaceholder = "Filter logs"
  static let logsViewerTitle = "Logs viewer"
  static let logsViewerNoMatchingLogs = "No logs match the filter"
  static let memoryWarningContent = "The model you've selected may exceed your device's memory, which can cause the app to crash. For the best experience, we recommend trying a smaller model."
  static let memoryWarningProceedAnyway = "Proceed anyway"
  static let memoryWarningTitle = "Memory Warning"
  static let maxTokensWarningMessage = "Setting max tokens above 10000 may cause app to be unstable."
  static let modelIsInitializingMsg = "Initializing model…"
  static let modelListImportedModelsTitle = "Imported models"
  static let modelListRecommendedModelsTitle = "Recommended models"
  static let modelManager = "Model Manager"
  static let modelManagerSelectTaskTitle = "Select a use case to try"
  static let modelNotDownloadedMsg = "Model not downloaded yet"
  static let name = "Name"
  static let noCutoutsCollected = "No cutouts collected"
  static let notificationContentFail = "Failed to download model \"%s\""
  static let notificationContentSuccess = "Model \"%s\" has been downloaded"
  static let notificationTitleFail = "Model download failed"
  static let notificationTitleSuccess = "Model download succeeded"
  static let ok = "OK"
  static let pasteFromClipboard = "Paste from clipboard"
  static let pickFromAlbum = "Pick from album"
  static let preview = "Preview"
  static let releaseToSend = "Release to send"
  static let replace = "Replace"
  static let results = "Results"
  static let reset = "Reset"
  static let resetNote = "Tapping \"Reset\" will reset LiteRT-LM engine only. The game progress won't be affected."
  static let resettingEngine = "Resetting engine..."
  static let restoreDefault = "Restore default"
  static let reinitializingDescription = "The game progress won't be affected"
  static let run = "Run"
  static let running = "Running..."
  static let runAgain = "Run again"
  static let runBenchmark = "Run benchmark"
  static let runBenchmarkConfirmationMsg = "This process typically takes several minutes and cannot be interrupted once started. Would you like to proceed?"
  static let runningBenchmarkMsg = "Running model benchmark..."
  static let save = "Save"
  static let secret = "Secret"
  static let selectDownloadedModel = "Select a downloaded model"
  static let selectModel = "Select a model"
  static let selectedCount = "%d selected"
  static let settingsDialogTosTitle = "Terms of service"
  static let settingsDialogViewAppTermsOfService = "View App Terms of Service"
  static let settingsDialogGemmaProhibitedUsePolicy = "Gemma Prohibited Use Policy"
  static let share = "Share"
  static let slideUpToCancel = "Slide up to cancel"
  static let systemPromptPlaceholder = "Enter system instructions (e.g., \"You are a versatile assistant. Provide accurate, context-aware responses in a professional tone.\")"
  static let systemPromptUpdated = "System prompt updated"
  static let submit = "Submit"
  static let takeAPicture = "Take a picture"
  static let tapToChangeColor = "Tap to change color"
  static let tapToSeeValue = "Tap on graph to see value"
  static let test = "Test"
  static let textImageGenerationTextFieldPlaceholder = "Type prompt…"
  static let textInputPlaceholderLlmChat = "Type prompt…"
  static let tosDialogTitleApp = "Welcome to Google AI Edge Gallery"
  static let tosDialogTitleGemma = "Gemma Terms of Use"
  static let tosDialogAcceptAndContinueButtonLabel = "Accept & continue"
  static let tosDialogAgreeAndContinueButtonLabel = "Agree & continue"
  static let tryIt = "Try it"
  static let turnOnAll = "Turn on all"
  static let turnOffAll = "Turn off all"
  static let undo = "Undo"
  static let unsupportedAction = "Unsupported action"
  static let setScreenBrightnessMessage = "I've set the screen brightness to %1$d%%."
  static let setTimerMessage = "Setting the timer for %1$d seconds."
  static let addCalendarEventMessage = "Adding \"Team meeting (10AM-11AM)\" to your calendar."
  static let takePictureMessage = "Opening the camera app."
  static let mobileActionsTitle = "Mobile Actions"
  static let mobileActionsDescription = "Control your device with simple commands"
  static let mobileActionsSupportedActions = "Supported sample actions:"
  static let mobileActionsTabModelResponse = "Model response"
  static let mobileActionsTabFunctionCalled = "Function(s) called"
  static let update = "Update"
  static let updateAvailable = "Update available"
  static let viewResults = "View results"
  static let viewConsoleLogs = "View console logs"
  static let warmingUp = "warming up…"
  static let warningNoFunctionCall = "No function recognized"
  static let snackbarNoFunctionCall = "No function recognized"
  static let unknownError = "Unknown error"
  static let view = "View"
  static let viewInFullScreen = "View in full screen"
  static let snackbarSaveToAlbumSuccess = "Saved to photo album"
  static let snackbarSaveToAlbumFailed = "Failed to save to photo album"
  static let snackbarCopyToClipboardSuccess = "Copied to clipboard"
  static let promptTemplateLabelFlashOnOff = "Turn flashlight on/off"
  static let promptTemplateLabelFlashOn = "Flashlight on"
  static let promptTemplateLabelFlashOff = "Flashlight off"
  static let promptTemplateLabelCreateContact = "Create contact"
  static let promptTemplateLabelSendEmail = "Send email"
  static let promptTemplateLabelCreateCalendarEvent = "Create calendar event"
  static let promptTemplateLabelShowLocationOnMap = "Show location on map"
  static let promptTemplateLabelOpenWifiSettings = "Open WIFI settings"
  static let mobileActionsChallengeTitle = "Mobile Actions Finetune Challenge"
  static let mobileActionsChallengeSubtitle = "Build it to play it!"
  static let mobileActionsChallengeDescription = "This demo is locked. To unlock the Mobile Actions agent, you need to compile the model yourself using our open-source recipe."
  static let mobileActionsChallengeInstructionsTitle = "Instructions:"
  static let mobileActionsChallengeInstruction1 = "1. <![CDATA[<b>On your computer</b>]]>, open <![CDATA[<a href=\"https://ai.google.dev/gemma/docs/mobile-actions\">this guide</a>]]>"
  static let mobileActionsChallengeInstruction2 = "2. Follow the instructions to fine tune the model and convert it to .litertlm format."
  static let mobileActionsChallengeInstruction3 = "3. Transfer the file to this phone."
  static let mobileActionsChallengeInstruction4 = "4. Tap <![CDATA[<b>Load Model</b>]]> below to unlock the demo."
  static let mobileActionsChallengeEmailColab = "Email guide to myself"
  static let mobileActionsChallengeLoadModel = "Load Model"
  static let aichatEmptystateTitle = "AI Chat"
  static let aichatEmptystateContent = "Chat with on-device large language models."
  static let addScript = "Add script"
  static let addDefaultScript = "Add default script"
  static let addSkill = "Add skill"
  static let addSkillOptionViewCommunitySkillsTitle = "View Community Skills"
  static let addSkillOptionViewCommunitySkillsDescription = "Explore community contributed skills on GitHub discussions"
  static let addSkillOptionFeaturedListTitle = "Add skill from featured list"
  static let addSkillOptionFeaturedListDescription = "Add a skill from a curated list of community contributed skills"
  static let addSkillOptionUrlTitle = "Load skill from URL"
  static let addSkillOptionUrlDescription = "Enter the URL of a skill directory hosted on Web"
  static let addSkillOptionLocalTitle = "Import local skill"
  static let addSkillOptionLocalDescription = "Import the skill directory locally"
  static let addSkillOptionSkillCreatorTitle = "Skill creator"
  static let addSkillOptionSkillCreatorDescription = "Create a skill from scratch in-app"
  static let addSkillFromUrlDialogTitle = "Add skill from URL"
  static let addSkillDialogTitleFromLocalImport = "Import local skill"
  static let addSkillDialogSubtitleFromLocalImport = "Please first \"adb push\" the whole skill directory to /sdcard/Download"
  static let addSkillManualInputSheetTitle = "Create a skill"
  static let agentSkills = "Agent Skills"
  static let disclaimerDialogContent = "Third-party skills are not authored or endorsed by Google. Google is not responsible for their contents, security, or data handling practices.\n\nPlease exercise caution before providing sensitive information, such as personal identification, tokens, or API keys.\n\nAny use of an Agent Skill is subject to the applicable terms for that Skill."
  static let disclaimerDialogTitle = "Add third-party skill"
  static let disclaimerDialogAgree = "Agree"
  static let deleteScriptDialogTitle = "Delete script"
  static let deleteSkillDialogTitle = "Delete skill"
  static let deleteSkillDialogContent = "Are you sure you want to delete the skill?"
  static let deleteSelectedSkillsTitle = "Delete selected skills"
  static let builtInSkillsTitle = "Built-in Skills"
  static let customSkillsTitle = "Custom Skills"
  static let describeRequirements = "Describe requirements"
  static let describeInputData = "Describe input data"
  static let describeInputDataSupportText = "The field names need to match the ones in instructions."
  static let describeOutputData = "Describe output data"
  static let duplicatedScriptName = "Duplicated script name"
  static let enableSkillDialogContent = "Please enable the skill by tapping the Skills button below."
  static let editSkill = "Edit skill"
  static let enterSkillUrl = "Enter URL of skill's root directory"
  static let featuredSkillsTitle = "Featured skills"
  static let featuredSkillsDescription = "A curated list of community contributed skills"
  static let generateLlmPromptTitle = "Generate LLM prompt"
  static let generateLlmPromptButtonLabel = "LLM prompt"
  static let learnHowToWriteSkills = "Learn how to write skills"
  static let loadingSkillsAllowlist = "Loading featured skills..."
  static let manageSkills = "Manage skills"
  static let manageSkillsDescription = "View, create, and manage your skills"
  static let skillLimitWarning = "Enabling more than %s may impact performance."
  static let noDirectorySelected = "No directory selected"
  static let pickSkillDir = "Pick skill's root directory"
  static let promptCopiedMessage = "Prompt copied to clipboard. Paste it into your favorite LLM app to generate the code and copy/paste the code here."
  static let promptChipKitchenAdventure = "Kitchen adventure"
  static let promptChipCalculateHash = "Calculate hash"
  static let promptChipQueryWikipedia = "Query Wikipedia"
  static let promptChipPlotChart = "Plot chart"
  static let promptChipInteractiveMap = "Interactive map"
  static let promptChipTextSpinner = "Spin label on my head"
  static let promptChipSendEmail = "Send email"
  static let replaceSkillDialogTitle = "Replace existing skill"
  static let replaceSkillDialogContent = "A skill with the same name already exists. Do you want to replace it?"
  static let searchSkill = "Search for a skill"
  static let selectScript = "Select script"
  static let scriptName = "Script name"
  static let scriptContent = "Script content"
  static let skills = "Skills"
  static let skillNameInputDescription = "REQUIRED. In the form of my-skill-name"
  static let skillDescriptionInputDescription = "REQUIRED. A brief description of the skill's function and trigger conditions or keywords."
  static let skillInstructionsInputDescription = "Detailed instructions in Markdown format that LLM must follow to accomplish the task."
  static let useCallJsTemplate = "Use Call JS template"
  static let mcp = "MCP"
  static let mcpToolCallPermissionTitle = "Permission to call MCP tool?"
  static let mcpToolNameLabel = "Tool name"
  static let mcpToolInputLabel = "Input"
  static let mcpToolAlwaysAllow = "Always allow"
  static let mcpToolAllowOnce = "Allow once"
  static let mcpToolDontAllow = "Don't allow"
  static let mcpToolRevoke = "Revoke"
  static let mcpToolRevokePermission = "Revoke tool call permission"
  static let mcpToolRevokePermissionTitle = "Revoke permission?"
  static let mcpToolRevokePermissionContent = "Are you sure you want to revoke permission to automatically call this tool?"
  static let manageMcpServers = "Manage MCP servers"
  static let addMcpServer = "Add MCP server"
  static let learnMoreAboutMcp = "Learn more about MCP in Google AI Edge Gallery"
  static let learnMoreAboutMcpShort = "Learn more"
  static let searchMcpServer = "Search for an MCP server"
  static let addMcpServerFromUrlDialogTitle = "Add MCP server from URL"
  static let enterMcpServerUrl = "Enter MCP server URL"
  static let deleteMcpServerDialogTitle = "Delete MCP server"
  static let deleteMcpServerDialogContent = "Are you sure you want to delete this MCP server?"
  static let manageTools = "Manage tools"
  static let mcpServerLabel = "MCP server: %s"
  static let mcpToolDescription = "Description"
  static let mcpToolSchema = "Schema"
  static let mcpDisclaimerDialogTitle = "Add third-party MCP"
  static let mcpDisclaimerDialogContent = "Third-party MCPs are not authored or endorsed by Google. Google is not responsible for their contents, security, or data handling practices.\n\nPlease exercise caution before providing sensitive information, such as personal identification, tokens, or API keys.\n\nAny use of an MCP is subject to the applicable terms for that MCP."
  static let mcpServerDuplicateTitle = "Duplicate MCP server"
  static let mcpServerDuplicateContent = "This MCP server URL is already added."
  static let mcpServerAuthorization = "Authorization"
  static let mcpServerAuthNone = "None"
  static let mcpServerAuthRequestHeader = "Request header"
  static let mcpServerAuthOauthWip = "OAuth (WIP)"
  static let mcpServerHeaderName = "Header name"
  static let mcpServerHeaderValue = "Header value"
  static let chatHistoryTitle = "Chat history"
  static let newChat = "New chat"
  static let clearAll = "Clear all"
  static let chatHistoryDemoNotice = "Chat history does not persist across demos."
  static let clearHistoryDialogTitle = "Clear history?"
  static let clearHistoryDialogContent = "Are you sure you want to clear the history? This action cannot be undone."
  static let cdAddIcon = "Add"
  static let cdImportModelButton = "Import model"
  static let cdTaskCard = "%1$s task with %2$d models"
  static let cdError = "Error"
  static let cdImportModelFromLocalFileButton = "Import model from local file"
  static let cdNavigateBackIcon = "Go back"
  static let cdAppSettingsIcon = "Settings"
  static let cdDoneIcon = "Done"
  static let cdCollapseIcon = "Collapse"
  static let cdExpandIcon = "Expand"
  static let cdStopIcon = "Stop"
  static let cdDeleteIcon = "Delete"
  static let cdCloseIcon = "Close"
  static let cdSelectedIcon = "Selected"
  static let cdModelSettingsIcon = "Model settings"
  static let cdResetSessionIcon = "Reset session"
  static let cdChangeModel = "Current model is %1$s. Tap to change model."
  static let cdCloseImageViewerIcon = "Close image viewer"
  static let cdCopyToClipboardIcon = "Copy to clipboard"
  static let cdPromptInputTextField = "Prompt input"
  static let cdSendPromptIcon = "Send prompt"
  static let cdModelResponseText = "Model response text"
  static let cdClearInputHistoryIcon = "Clear input history"
  static let cdDeleteInputHistoryEntryIcon = "Delete input history entry"
  static let cdContentInputField = "Content input"
  static let cdAddExamplePromptIcon = "Add example prompt"
  static let cdImageThumbnail = "Image thumbnail"
  static let cdUserImage = "User image %1$d"
  static let cdUserImageInGroup = "User image %1$d of %2$d"
  static let cdAddContentIcon = "Add content"
  static let cdCameraShutterIcon = "Camera shutter"
  static let cdToggleFrontBackCameraIcon = "Toggle front or back camera"
  static let cdPickFile = "Pick file"
  static let cdPlayAudioIcon = "Play audio"
  static let cdStopPlaybackIcon = "Stop playback"
  static let cdSendAudioClipIcon = "Send audio clip"
  static let cdStartRecording = "Start recording"
  static let cdDownloadedIcon = "Downloaded"
  static let cdNotDownloadedIcon = "Not downloaded"
  static let cdDownloadingIcon = "Downloading"
  static let cdDownloadFailedIcon = "Download failed"
  static let cdChatPanel = "Chat panel"
  static let cdSwitchToKeyboard = "Switch to keyboard"
  static let cdSwitchToVoice = "Switch to voice"
  static let cdShowHistory = "Show history"
  static let cdMoreOptions = "More options"
  static let cdHelp = "Help"
  static let cdMenu = "Menu"
  static let cdScrollToBottom = "Scroll to bottom"
  static let cdChatHistory = "Chat history"

  // Plurals from strings.xml (quantity one/other) as functions.
  static func modelListNumberOfModelsAvailable(_ count: Int) -> String {
    let fmt = count == 1 ? "%d model available" : "%d models available"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func runs(_ count: Int) -> String {
    let fmt = count == 1 ? "%d run" : "%d runs"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func parameter(_ count: Int) -> String {
    let fmt = count == 1 ? "Parameter" : "Parameters"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func deleteSelectedSkillsContent(_ count: Int) -> String {
    let fmt = count == 1 ? "Are you sure you want to delete %d skill?" : "Are you sure you want to delete %d skills?"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func selectedCustomSkillsCount(_ count: Int) -> String {
    let fmt = count == 1 ? "%d selected" : "%d selected"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func skillsCount(_ count: Int) -> String {
    let fmt = count == 1 ? "%d skill" : "%d skills"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func mcpServersCount(_ count: Int) -> String {
    let fmt = count == 1 ? "%d MCP server" : "%d MCP servers"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
  static func mcpToolsCount(_ count: Int) -> String {
    let fmt = count == 1 ? "%d tool" : "%d tools"
    return String(format: fmt.replacingOccurrences(of: "%d", with: "%d"), count)
  }
}
